### ISSUE TITLE
Satic message time

### ISSUE THREAD

**Issue by Rebbit13** [bodrovis-learning/Python-SOLID-video#1]
Здравствуйте,

В данной строчке 
https://github.com/bodrovis-learning/Python-SOLID-video/blob/9e9ec568a9cdbbe53362533abf20586cc9f994eb/ocp/after.py#L7
у Вас устанавливается статичное время на момент создания инстанса. Для нескольких сообщений созданных в разное время в сообщении время будет одно и то же. 

Я бы предложил сохранять в атрибут не функцию, а формат как строку а в самом методе log подтягивать в функцию формата времени только формат.

**Comment by bodrovis** [comment]
Да уж, это глупость я сделал, конечно. То есть в целом для демонстрации идеи это не столь важно, но очень глупо вышло. Я поправлю и добавлю коммент под видео. Спасибо!
